---
title: "Instacart Dashboard"
author: "He Jin & Chuhan Zhou"
date: "11/15/2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
instacart = read_csv("../data/orders_train_allvars.csv") %>%
  clean_names() 
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>% 
  group_by(department) %>%
  summarize(items_ordered = n()) %>%
  mutate(department = as.factor(department),
         department = fct_reorder(department, items_ordered)) %>% 
  plot_ly(x = ~department, y = ~items_ordered, 
          color = ~department, type = "bar", alpha = 0.8) 
```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart B

```{r}
  aisle_top = instacart %>%
  group_by(department,aisle) %>%
  summarize(items_ordered = n()) %>%
  top_n(3) %>%
  ungroup() %>%
  mutate(aisle = as.factor(aisle),
         aisle = fct_reorder(aisle, items_ordered)) 
  plot_ly(aisle_top,x = ~aisle, y = ~items_ordered, type = "bar",
          alpha = 0.5, 
          color = ~aisle) %>%
  layout(showlegend = FALSE)
```

### Chart C

```{r}
instacart %>%

  filter(aisle == aisle_top$aisle) %>%
  group_by(order_dow,aisle) %>%
  plot_ly(x = ~aisle, y = ~order_hour_of_day, color = ~aisle, type = "box", colors = "Set2") %>%
  layout(showlegend = FALSE)

```
